import {applyEvent,type ResearchClient,type ProblemInput,type Snapshot,type ResearchEvent,type Update,type Idea,type Experiment} from './contracts';
const ideas:Idea[]=[
{id:'01',title:'Two parallel routes',description:'Unit nonatomic demand chooses between delays x and c. Compare selfish routing with the social optimum.',parents:[],operation:'seed',inactive:false,c:.3},
{id:'02',title:'Raise the fixed delay',description:'Increase c to 0.6 to seek a stronger inefficiency witness.',parents:['01'],operation:'mutation',mutation:'Raise c from 0.3 to 0.6.',inactive:true,c:.6},
{id:'03',title:'Exact flow certificates',description:'At c = 0.8, certify equilibrium x = c and optimal flow x = c/2 algebraically.',parents:['01'],operation:'mutation',mutation:'Use exact flow certificates.',inactive:false,c:.8},
{id:'04',title:'Try an infeasible flow',description:'This attempted implementation assigns 1.2 units despite unit demand. Preserve its failed evidence.',parents:['01'],operation:'mutation',mutation:'Perturb the flow allocation.',inactive:true,c:.4},
{id:'05',title:'A simple rational witness',description:'Set c = 9/10. Retain this in the illustrative simple-certificate category.',parents:['02'],operation:'mutation',mutation:'Refine c to 9/10.',inactive:false,c:.9},
{id:'06',title:'Search + exact verification',description:'Combine #02’s upward search and #03’s exact certificates. Evaluate c = 0.95; no extra mutation.',parents:['02','03'],operation:'merge',inactive:false,c:.95},
{id:'07',title:'Include the boundary',description:'Merge #02’s parameter search with #03’s certificates, then add the endpoint. Recover the known sharp 4/3 ratio.',parents:['02','03'],operation:'merge_mutation',mutation:'Include c = 1 rather than only interior points.',inactive:false,c:1}];
export function witness(c:number){return {poa:1/(1-c/4),equilibrium:c,optimum:c-c*c/4}}
export class MockResearchClient implements ResearchClient {
 private state?:Snapshot;private events:ResearchEvent[]=[];private listeners=new Set<(e:ResearchEvent)=>void>();private timers=new Set<ReturnType<typeof setTimeout>>();private next=0;private active=0;
 constructor(private delay=1400){}
 private require(id:string){if(!this.state||this.state.run.id!==id)throw Error('Run not found');return this.state}
 private emit(update:Update){const s=this.state!;const e={...update,schemaVersion:1 as const,runId:s.run.id,eventId:crypto.randomUUID(),sequence:s.sequence+1,timestamp:new Date().toISOString()} as ResearchEvent;this.state=applyEvent(s,e);this.events.push(e);this.listeners.forEach(l=>l(e))}
 private log(category:string,message:string,ideaId?:string){this.emit({type:'log_added',payload:{id:crypto.randomUUID(),timestamp:new Date().toISOString(),category,message,ideaId}})}
 async startRun(input:ProblemInput){if(input.mode!=='demo')throw Error('Only the explicit demo is available');if(this.state&&['running','pausing','paused','stopping'].includes(this.state.run.status))throw Error('Stop the active run first');this.clear();this.events=[];this.next=0;this.active=0;this.state={run:{id:crypto.randomUUID(),title:'How inefficient can selfish routing be?',status:'running',startedAt:new Date().toISOString()},ideas:[],experiments:[],elites:[],logs:[],sequence:0};this.log('start','Demo: Pigou network, unit demand. Known target: 4/3.');this.pump();return {...this.state.run}}
 async getSnapshot(id:string){return structuredClone(this.require(id))}
 subscribe(id:string,after:number,listener:(e:ResearchEvent)=>void){this.require(id);this.events.filter(e=>e.sequence>after).forEach(listener);this.listeners.add(listener);return ()=>{this.listeners.delete(listener)}}
 async pauseRun(id:string){if(this.require(id).run.status!=='running')return;this.emit({type:'run_status_changed',payload:{status:'pausing'}});this.log('control','Pause requested; active experiments will finish.');this.settle()}
 async resumeRun(id:string){if(this.require(id).run.status!=='paused')return;this.emit({type:'run_status_changed',payload:{status:'running'}});this.log('control','Lab resumed.');this.pump()}
 async stopRun(id:string){const s=this.require(id);if(['completed','stopped','failed'].includes(s.run.status))return;this.emit({type:'run_status_changed',payload:{status:'stopping'}});this.clear();for(const e of s.experiments.filter(e=>e.status==='running'))this.emit({type:'experiment_updated',payload:{...e,status:'cancelled',feedback:'Stopped by user.'}});this.active=0;this.log('control','Lab stopped. Evidence retained.');this.emit({type:'run_status_changed',payload:{status:'stopped',endedAt:new Date().toISOString()}})}
 private pump(){if(this.state?.run.status!=='running')return;while(this.active<2&&this.next<ideas.length){const idea=ideas[this.next];if(idea.parents.some(id=>!this.state!.experiments.some(e=>e.ideaId===id&&e.status==='completed')))break;this.next++;this.active++;this.emit({type:'idea_created',payload:idea});const e:Experiment={id:'exp-'+idea.id,ideaId:idea.id,status:'running',valid:null,metrics:{},feedback:''};this.emit({type:'experiment_updated',payload:e});this.log('propose',idea.title+' · '+idea.operation.replaceAll('_',' + '),idea.id);const timer=setTimeout(()=>{this.timers.delete(timer);this.finish(idea,e)},this.delay*(idea.id==='02'?2:1));this.timers.add(timer)}this.settle()}
 private finish(i:Idea,e:Experiment){this.active--;const valid=i.id!=='04';this.emit({type:'experiment_updated',payload:{...e,status:valid?'completed':'failed',valid,metrics:valid?witness(i.c):{},feedback:valid?'Analytic check: equilibrium x = c; optimum x = c/2 for 0 < c ≤ 1.':'Rejected: flow 1.2 exceeds unit demand.'}});this.log(valid?'verify':'failure',valid?`PoA = ${witness(i.c).poa.toFixed(4)}. Analytic example value.`:'Invalid flow. No score assigned.',i.id);if(['03','05','07'].includes(i.id)){const niche=i.id==='05'?'Simple certificate':'Strongest witness';for(const old of this.state!.elites.filter(e=>e.current&&e.niche===niche))this.emit({type:'elite_changed',payload:{...old,current:false}});this.emit({type:'elite_changed',payload:{ideaId:i.id,experimentId:e.id,niche,current:true}});this.log('archive','Elite retained: '+niche+' (demo policy).',i.id)}this.pump();this.settle()}
 private settle(){if(this.active)return;if(this.state?.run.status==='pausing'){this.emit({type:'run_status_changed',payload:{status:'paused'}});this.log('control','Lab paused.')}else if(this.state?.run.status==='running'&&this.next===ideas.length){this.log('complete','Known sharp witness recovered: 1 / (3/4) = 4/3.');this.emit({type:'run_status_changed',payload:{status:'completed',endedAt:new Date().toISOString()}})}}
 private clear(){this.timers.forEach(clearTimeout);this.timers.clear()}
 dispose(){this.clear();this.listeners.clear()}
}
